language: node_js
node_js:
  - "node"
addons:
  chrome: stable
services:
  - xvfb
before_install:
  - npm run echo:v
  - cp ./README.md ./packages/cheetah-grid/README.md
  - cp ./LICENSE ./packages/cheetah-grid/LICENSE
  - cp ./LICENSE ./packages/vue-cheetah-grid/LICENSE

before_script:
  - npm run install:all
  - npm run lint
  - npm run build:ci
  - npm run check

deploy:
  skip_cleanup: true
  provider: script
  script: sh $TRAVIS_BUILD_DIR/deploy.sh
  on:
    tags: true

notifications:
  email: false