name: publish

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: check version, and release
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup Node
      uses: actions/setup-node@v2
      with:
        registry-url: 'https://registry.npmjs.org'
    - name: Install Packages
      run: |+
        npm ci
        npm run ci:all
    - name: Build
      run: npm run build:ci
    - name: test
      run: npm run test -- --mrpm-max-workers=1
    - name: release
      run: |+
        npm run echo:v
        cp ./README.md ./packages/cheetah-grid/README.md
        cp ./LICENSE ./packages/cheetah-grid/LICENSE
        cp ./LICENSE ./packages/vue-cheetah-grid/LICENSE
        cp ./LICENSE ./packages/cheetah-grid-icon-svg-loader/LICENSE
        npm run publish:all
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: peter-evans/create-pull-request@v7
      with:
        commit-message: post-release updates
        branch: post-release
        branch-suffix: timestamp
        title: post-release updates
        base: master
